import type { Metadata } from "next";
import { Zen_Dots, Roboto_Flex, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BeamsBackgroundWrapper from "@/components/BeamsBackgroundWrapper";

const zendots = Zen_Dots({
  variable: "--font-zen-dots",
  weight:"400"
});

const robotoFlex = Roboto_Flex({
  variable: "--font-roboto-flex",
  weight:["100","200","300","400","500","600","700","800","900","1000"]
});
const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700"
  ],
});

export const metadata: Metadata = {
  title: "ConstructDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zendots.variable} ${robotoFlex.variable} ${robotoMono.variable} antialiased relative overflow-x-hidden bg-black min-h-screen`}
      >
        <div className="fixed inset-0 -z-10 pointer-events-none h-full w-full">
          {/* Only render BeamsBackground on desktop - lazy load it */}
          <div className="hidden sm:block">
            <BeamsBackgroundWrapper />
          </div>

          {/* Lightweight gradient fallback for mobile */}
          <div className="sm:hidden bg-linear-to-b from-[#001B66] to-black opacity-40" />
        </div>
        <div className="relative z-10">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
